version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  generate_study_population_measures:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_practice_measures --output-format feather --index-date-range "2019-03-01 to 2021-02-01 by month" --output-dir=output/practice_measures
    outputs:
      highly_sensitive:
        cohort: output/practice_measures/input_*.feather

  generate_practice_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition_practice_measures --output-dir=output/practice_measures
      needs: [generate_study_population_measures]
      outputs:
        moderately_sensitive:
          measure_csv: output/practice_measures/measure_*.csv

  generate_report:
    run: cohort-report:v3.0.0 output/input.feather
    needs: [generate_study_population]
    config:
      output_path: output/cohort_reports_outputs
    outputs: 
      moderately_sensitive:
        report: output/cohort_reports_outputs/descriptives_input.html
        report_charts: output/cohort_reports_outputs/*.png

  describe_cohorts:
    run: r:latest analysis/01_describe_cohorts.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        deaths_cohort: output/describe_cohorts/deaths_cohort.csv
        deaths_quarter: output/describe_cohorts/deaths_quarter.csv
        deaths_quarter_figure: output/describe_cohorts/deaths_quarter.png
        deaths_cohort_pod: output/describe_cohorts/deaths_cohort_pod.csv
        deaths_quarter_pod: output/describe_cohorts/deaths_quarter_pod.csv
        deaths_pod_figures: output/describe_cohorts/deaths_pod_cohort*.png
        deaths_month_ons: output/describe_cohorts/deaths_month*.csv
        deaths_ratio: output/describe_cohorts/deaths_ratio*.csv

  describe_service_use:
    run: r:latest analysis/02_describe_service_use.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        service_use_means: output/describe_service_use/service_use_mean*.csv
        service_use_ratios: output/describe_service_use/service_use_ratio*.csv
