version: '3.0'

expectations:
  population_size: 10000

actions:
  generate_cohort:
    run: >
      cohortextractor:latest
        generate_cohort --study-definition study_definition_validation
        --output-file output/cohort.csv
    outputs:
      highly_sensitive:
        cohort: output/cohort.csv

  generate_dataset:
    run: >
      databuilder:v0
        generate-dataset analysis/dataset_definition.py
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv

  count_medication_events:
    run: >
      python:latest
        python analysis/count_medication_events.py
    needs: [generate_cohort, generate_dataset]
    outputs:
      moderately_sensitive:
        counts: output/medication-counts.json
