version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  generate_report:
    run: cohort-report:v3.0.0 output/input.feather
    needs: [generate_study_population]
    config:
      output_path: output/cohort_reports_outputs
    outputs: 
      moderately_sensitive:
        report: output/cohort_reports_outputs/descriptives_input.html
        report_charts: output/cohort_reports_outputs/*.png

  describe_cohorts:
    run: r:latest analysis/01_describe_cohorts.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        deaths_cohort: output/describe_cohorts/overall_death_counts/deaths_cohort.csv
        deaths_quarter: output/describe_cohorts/overall_death_counts/deaths_quarter.csv
        deaths_quarter_figure: output/describe_cohorts/overall_death_counts/deaths_quarter.png
        deaths_cohort_pod: output/describe_cohorts/overall_death_counts/deaths_cohort_pod*.csv
        deaths_quarter_pod: output/describe_cohorts/overall_death_counts/deaths_quarter_pod.csv
        deaths_pod_figures: output/describe_cohorts/overall_death_counts/deaths_pod_cohort*.png
        deaths_quarter_characteristic: output/describe_cohorts/quarter_death_counts/deaths_quarter_*.csv
        quarter_summary_table: output/describe_cohorts/quarter_summary_table.csv
        quarter_pod_summary_table: output/describe_cohorts/quart_pod_summary_table.csv
        deaths_quarter_ons: output/describe_cohorts/ons_death_comparisons/deaths_ons_quarter*.csv
        deaths_month_ons: output/describe_cohorts/ons_death_comparisons/deaths_ons_month*.csv
        deaths_ons_plots: output/describe_cohorts/ons_death_comparisons/deaths_ons*.png
        cohort_summary_table: output/describe_cohorts/cohorts_summary_table.csv
        cohort_pod_summary_table: output/describe_cohorts/cohorts_pod_summary_table.csv
        death_ratios_cohort: output/describe_cohorts/death_ratios_cohort/death_ratio_cohort*.csv
        death_ratios_pod_cohort: output/describe_cohorts/death_ratios_pod_cohort/death_ratio_pod_cohort*.csv

  describe_service_use:
    run: r:latest analysis/02_describe_service_use.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        service_use_means: output/describe_service_use/service_use_mean*.csv
        gp_complete_service_use_means: output/describe_service_use/complete_gp_history/gp_service_use_mean*.csv
        service_use_ratios: output/describe_service_use/service_use_ratio*.csv
