version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_medication_codelist_comprison_dataset:
    run: >
      databuilder:v0
        generate-dataset analysis/dataset_definition.py
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv

  validate_medication_codelist_counts:
    run: >
      python:latest
        python analysis/validate_prescription_counts.py
    needs: [generate_medication_codelist_comprison_dataset]
    outputs:
      moderately_sensitive:
        totals: output/validation_totals.csv
