version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition 
    #--output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  #generate_report:
  #  run: cohort-report:v3.0.0 output/input.csv
  #  needs: [generate_study_population]
  #  config:
  #    output_path: output/cohort_reports_outputs
  #outputs: 
  #  moderately_sensitive:
  #    reports: output/cohort_reports_outputs/descriptives_input.html

  describe:
    run: r:latest analysis/XX_dod_histogram.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        cohort: output/dod_histogram.png