version: '3.0'

expectations:
  population_size: 10000

actions:
  generate_dataset:
    run: >
      databuilder:v0
        generate-dataset analysis/dataset_definition.py
        --output output/dataset.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset.csv

  count_medication_events:
    run: >
      python:latest
        python analysis/count_medication_events.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        counts: output/medication-counts.json
